FROM node:18
WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
COPY prisma ./prisma
ARG DATABASE_URL
ARG DIRECT_URL
ENV DATABASE_URL=$DATABASE_URL
ENV DIRECT_URL=$DIRECT_URL
RUN npx prisma migrate deploy
EXPOSE 3000
CMD ["npm", "start"]
