name: Deploy API (Node.js with Docker, Prisma, and PostgreSQL) to Vercel

on:
  push:
    branches:
      - api-prod

jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate Docker image tag
        id: image_tag
        run: echo "IMAGE_TAG=my-api-app-${{ github.sha }}" >> $GITHUB_ENV

      - name: Log Environment Variables in Actions
        run: |
          echo "DATABASE_URL=${DATABASE_URL}"
          echo "DIRECT_URL=${DIRECT_URL}"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}

      - name: Build Docker image for API
        run: |
          docker build -t ${{ env.IMAGE_TAG }} \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg DIRECT_URL=${{ secrets.DIRECT_URL }} ./api

      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Debug Vercel Token
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [ -z "$VERCEL_TOKEN" ]; then
            echo "VERCEL_TOKEN is empty!"
            exit 1
          else
            echo "VERCEL_TOKEN is set"
          fi
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --token "$VERCEL_TOKEN" --yes